refactoring and don't require ruby 3

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -3,8 +3,8 @@ set -euo pipefail
 IFS=$'\n\t'
 set -vx
 
-if ! ruby -v 2>/dev/null | grep -q "^ruby 3\.0\."; then
-  echo "ruby 3.0.0 required, we recommend rbenv or rvm!"
+if ! ruby -v 2>/dev/null | grep -q "^ruby 2\.6\."; then
+  echo "ruby 2.6.3 required, we recommend rbenv or rvm!"
   exit 1
 fi
 
